export const MIN_GATHERING_NAME_LENGTH = 1;
export const MAX_GATHERING_NAME_LENGTH = 50;
export const MAX_GATHERING_DESCRIPTION_LENGTH = 100;
export const MIN_GATHERING_COUNT = 2;
export const MAX_GATHERING_COUNT = 8;
export const DEFAULT_GATHERING_COUNT = 3;

if (DEFAULT_GATHERING_COUNT > MAX_GATHERING_COUNT) throw new Error('DEFAULT_GATHERING_COUNT cannot be greater than MAX_GATHERING_COUNT');
if (DEFAULT_GATHERING_COUNT < MIN_GATHERING_COUNT) throw new Error('DEFAULT_GATHERING_COUNT cannot be less than MIN_GATHERING_COUNT');
